export const SiteConfig = {
  title: "Vibranic-central",
  description: "Generated by create next app",
  keywords: [
    'vibranic', 
    'central', 
    'vibranic-central', 
    'vibranic central',
  ],
  // url: env.NEXT_PUBLIC_SITE_URL || 'https://vibranic-central.be',
  // googleSiteVerification: env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION || '',
}